name: klashalunchapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.6
  flutter_screenutil: ^5.7.0
  flutter_easyloading: ^3.0.5
  google_fonts: ^4.0.4
  retrofit: ^4.0.1
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^6.0.0+2
  build_runner: any

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/


